- hosts: local
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home_dir: "/home/{{ user }}"
  roles:
    - pre_build
    - python
    - redis
    - postgres
    - ruby
    - rails
